### ISSUE TITLE
There is no code in this repo

### ISSUE THREAD

**Issue by sdshlanta** [cyclawps52/DSU-MacPrint#1]
There is no code in the repo only a zip with the code in it!  Doesn't this defeat the point of github?

**Comment by cyclawps52** [comment]
The wwp.scpt file is the applescript code for the app. Unfortunately, Github does not display this inline unlike other languages.

**Comment by cyclawps52** [comment]
This is fixed in the latest commit (I didn't realize the source was precompiled, my bad!)
https://github.com/cyclawps52/DSU-MacPrint/blob/master/sourceCode.applescript
